config/routes.rb
Medicalapp::Application.routes.draw do

  resources :patient_documents
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users do
    member do
      get 'admin'
    end
  end
  resources :patients do
    collection do
      get 'upload'
      get 'archived'
    end
    member do 
      get 'archive'
      get 'unarchive'
    end
  end

  resources :children do
    collection do
      get 'upload'
      get 'archived'
    end
    member do
      get 'archive'
      get 'unarchive'
    end
  end

  root :to => "patients#index"

end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_admin!, :only => [:archived, :archive, :unarchive, :edit]
  # GET /children
  # GET /children.xml
  def index
    respond_to do |format|
      format.html {}
      format.json {
        @children = Child.where(:archive => false).jtable_basic_query(params[:jTableQuery])
        render :json => jtable_for_json(:basic, @children, params[:jTableQuery])
      }
      format.xml  { render :xml => @icd_codes }
      format.xls  {@children = Child.all}
    end
  end 
  def archived
    respond_to do |format|
      format.html {}
      format.json {
        @children = Child.where(:archive => true).jtable_basic_query(params[:jTableQuery])
        render :json => jtable_for_json(:basic, @children, params[:jTableQuery])
      }
      format.xml  { render :xml => @icd_codes }
    end
  end

  # GET /children/1
  # GET /children/1.xml
  def show
    @child = Child.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { render :xml => @children }
    end
  end

  # GET /children/new
  # GET /children/new.xml
  def new
    @child = Child.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @children }
    end
  end

  # GET /children/1/edit
  def edit
    @child = Child.find(params[:id])
  end

  # POST /children
  # POST /children.xml
  def create
    if params[:child][:upload]
      file = params[:child][:upload].read
      file.each_line do |child|
        ovc_id, name, address, contact_no, age, sex, hiv_status, weight, treatment_code_of_parent, treatment_type, support_group, location, school, class_form, support_received, caregiver_name, plcode, caregiver_relationship, caregiver_contact_no, caregiver_address, caregiver_age, caregiver_occupation = child.chomp.split(",")
        Child.create!(:ovc_id => ovc_id, :name => name, :address => address, :contact_no => contact_no, :age => age, :sex => sex, :hiv_status => hiv_status, :weight => weight, :treatment_code_of_parent => treatment_code_of_parent, :treatment_type => treatment_type, :support_group => support_group, :location => location, :school => school, :class_form => class_form, :support_received => support_received, :caregiver_name => caregiver_name, :plcode => plcode, :caregiver_relationship => caregiver_relationship, :caregiver_contact_no => caregiver_contact_no, :caregiver_address => caregiver_address, :caregiver_age => caregiver_age, :caregiver_occupation => caregiver_occupation)
      end
      redirect_to(children_url)
    else
      @child = Child.new(params[:child])
      respond_to do |format|
        if @child.save
          format.html { redirect_to(@child, :notice => 'Child was successfully created.') }
          format.xml  { render :xml => @child, :status => :created, :location => @child }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @child.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /children/1
  # PUT /children/1.xml
  def update
    @children = Child.find(params[:id])

    respond_to do |format|
      if @children.update_attributes(params[:child])
        format.html { redirect_to(@children, :notice => 'Child was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @children.errors, :status => :unprocessable_entity }
      end
    end
  end

  def upload
    @child = Child.new
  end
  
  def archive
    @children = Child.find(params[:id])
    @children.archive = true
    @children.save
    
    respond_to do |format|
      format.html {redirect_to(children_url) }
    end
  end
  
  def unarchive
    @children = Child.find(params[:id])
    @children.archive = false
    @children.save
    
    respond_to do |format|
      format.html {redirect_to(archived_children_path) }
    end
  end
  
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_form.html.erb
<%= form_for(@child, :html => {:multipart => true}) do |f| %>
  <% if @child.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@child.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :ovc_id %><br />
    <%= f.text_field :ovc_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :contact_no %><br />
    <%= f.text_field :contact_no %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :hiv_status %><br />
    <%= f.text_field :hiv_status %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :treatment_code_of_parent %><br />
    <%= f.text_field :treatment_code_of_parent %>
  </div>
  <div class="field">
    <%= f.label :treatment_type %><br />
    <%= f.text_field :treatment_type %>
  </div>
  <div class="field">
    <%= f.label :support_group %><br />
    <%= f.text_field :support_group %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :school %><br />
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :class_form %><br />
    <%= f.text_field :class_form %>
  </div>
  <div class="field">
    <%= f.label :support_received %><br />
    <%= f.text_field :support_received %>
  </div>
  <div class="field">
    <%= f.label :caregiver_name %><br />
    <%= f.text_field :caregiver_name %>
  </div>
  <div class="field">
    <%= f.label :plcode %><br/>
    <%= f.text_field :plcode %>
  </div>
  <div class="field">
    <%= f.label :caregiver_relationship %><br />
    <%= f.text_field :caregiver_relationship %>
  </div>
  <div class="field">
    <%= f.label :caregiver_contact_no %><br />
    <%= f.text_field :caregiver_contact_no %>
  </div>
  <div class="field">
    <%= f.label :caregiver_address %><br />
    <%= f.text_field :caregiver_address %>
  </div>
  <div class="field">
    <%= f.label :caregiver_age %><br />
    <%= f.text_field :caregiver_age %>
  </div>
  <div class="field">
    <%= f.label :caregiver_occupation %><br />
    <%= f.text_field :caregiver_occupation %>
  </div>
  <div class="field">
    <%= f.label "Upload Picture" %><br />
    <%= f.file_field :picture %>
  </div>

  <%= image_tag @child.picture.url unless @child.picture.url.blank? %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/children/archived.html.erb
<h1>Listing archived children patients</h1>

<div id="children"></div>
<script type="text/javascript" charset="utf-8">
  $('#children').jTable({
    width: '100%',
    indexUrl: '/children/archived.json',
    viewUrl: '/children/:id:',
    editUrl: '/children/:id:/edit',
    destroyLink: false,
    singleColumnSearch: true,
    columns: [
      {heading: 'OVC id', attribute: 'ovc_id'},
      {heading: 'Name', attribute: 'name'},
      {heading: 'Address', attribute: 'address'},
      {heading: 'Contact Number', attribute: 'contact_no'},
      {heading: 'Age', attribute: 'age'},
      {heading: 'Sex', attribute: 'sex'},
      {heading: 'HIV status', attribute: 'hiv_status'},
      {heading: 'weight', attribute: 'weight'},
      {heading: 'Parent Treatment Code', attribute: 'treatment_code_of_parent'},
      {heading: 'Treatment', attribute: 'treatment_type'},
      {heading: 'Support Group', attribute: 'support_group'},
      {heading: 'Location', attribute: 'location'},
      {heading: 'School', attribute: 'school'}
    ],
    otherActions: [
      {title: 'Restore', href: '/children/:id:/unarchive'}
    ]
  })
</script>

<br />

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render 'form' %>

<%= link_to 'Show', @child %> |
<%= link_to 'Back', children_path %>

app/views/children/index.html.erb
<h1>Listing children patients</h1>

<div id="children"></div>
<script type="text/javascript" charset="utf-8">
  $('#children').jTable({
    width: '100%',
    indexUrl: '/children.json',
    viewUrl: '/children/:id:',
    editUrl: '/children/:id:/edit',
    destroyLink: false,
    singleColumnSearch: true,
    columns: [
      {heading: 'OVC id', attribute: 'ovc_id'},
      {heading: 'Name', attribute: 'name'},
      {heading: 'Address', attribute: 'address'},
      {heading: 'Contact Number', attribute: 'contact_no'},
      {heading: 'Age', attribute: 'age'},
      {heading: 'Sex', attribute: 'sex'},
      {heading: 'HIV status', attribute: 'hiv_status'},
      {heading: 'weight', attribute: 'weight'},
      {heading: 'Parent Treatment Code', attribute: 'treatment_code_of_parent'},
      {heading: 'Treatment', attribute: 'treatment_type'},
      {heading: 'Support Group', attribute: 'support_group'},
      {heading: 'Location', attribute: 'location'},
      {heading: 'School', attribute: 'school'}
    ],
    otherActions: [
      {title: 'Archive', href: '/children/:id:/archive'}
    ]
  })
</script>

<br />
<%= link_to "Archived Children Patients", archived_children_path %><br />
<%= link_to 'New Child', new_child_path%><br />
<%= link_to "Upload Children Patients File", upload_children_path %><br />
<%= link_to "Download Children as Excel", children_path(:format => :xls) %> 

app/views/children/new.html.erb
<h1>New child</h1>

<%= render 'form' %>

<%= link_to 'Back', children_path %>

app/views/children/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Ovc:</b>
  <%= @child.ovc_id %>
</p>

<p>
  <b>Name:</b>
  <%= @child.name %>
</p>

<p>
  <b>Address:</b>
  <%= @child.address %>
</p>

<p>
  <b>Contact no:</b>
  <%= @child.contact_no %>
</p>

<p>
  <b>Age:</b>
  <%= @child.age %>
</p>

<p>
  <b>Sex:</b>
  <%= @child.sex %>
</p>

<p>
  <b>Hiv status:</b>
  <%= @child.hiv_status %>
</p>

<p>
  <b>Weight:</b>
  <%= @child.weight %>
</p>

<p>
  <b>Treatment code of parent:</b>
  <%= @child.treatment_code_of_parent %>
</p>

<p>
  <b>Treatment type:</b>
  <%= @child.treatment_type %>
</p>

<p>
  <b>Support group:</b>
  <%= @child.support_group %>
</p>

<p>
  <b>Location:</b>
  <%= @child.location %>
</p>

<p>
  <b>School:</b>
  <%= @child.school %>
</p>
<p>
  <b>Class/Form:</b>
  <%= @child.class_form %>
</p>
<p>
  <b>Support Received:</b>
  <%= @child.support_received %>
</p>
<p>
  <b>Caregiver Name:</b>
  <%= @child.caregiver_name%>
</p>
<p>
  <b>PL Code:</b>
  <%= @child.plcode %>
</p>
<p>
  <b>Caregiver Relationship:</b>
  <%= @child.caregiver_relationship %>
</p>
<p>
  <b>Caregiver Contact Number:</b>
  <%= @child.caregiver_contact_no %>
</p>
<p>
  <b>Caregiver Address:</b>
  <%= @child.caregiver_address %>
</p>
<p>
  <b>Caregiver Age:</b>
  <%= @child.caregiver_age %>
</p>
<p>
  <b>Caregiver Occupation:</b>
  <%= @child.caregiver_occupation %>
</p>

<%= image_tag @child.picture.url unless @child.picture.url.blank? %><br />


<%= link_to 'Edit', edit_child_path(@child) %> |
<%= link_to 'Back', children_path %>

app/views/children/upload.html.erb
<%= form_for(@child, :html => {:multipart => true}) do |f| %>
  <div class="field">
    <%= f.label :upload, "Upload csv file in the format of 'name, address, telephone number, age, sex, treatment, source, plhiv code, plhiv name, support group, weight, treatment code, date_registered, occupation, marital status, children, line of treatment, next of kin, disclosed status, transfer in, transfer out, co infected, treatment default, type of service received, deceased' to add to the patient database"%><br /><br /><br />
    
    <%= f.file_field :upload %>
  </div>
  <div class="actions">
    <%= f.submit("Upload") %>
  </div>
<% end %>