config/routes.rb
Medicalapp::Application.routes.draw do

  resources :patient_documents
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users do
    member do
      get 'admin'
    end
  end
  resources :patients do
    collection do
      get 'upload'
      get 'archived'
    end
    member do 
      get 'archive'
      get 'unarchive'
    end
  end

  resources :children do
    collection do
      get 'upload'
      get 'archived'
    end
    member do
      get 'archive'
      get 'unarchive'
    end
  end

  root :to => "patients#index"

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  attr_accessor :upload
  
  jtable :basic, :name, :address, :age, :sex, :treatment, :source, :picture
  
  def jtable_basic_attribute_picture
    if self.picture.blank?
      false
    else
      true
    end
  end
  
  def jtable_basic_attribute_sex
    unless self.sex.blank?
      if self.sex.downcase == "m"
        "Male"
      elsif self.sex.downcase == "f"
        "Female"
      else
        self.sex
      end
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_admin!, :only => [:archived, :archive, :unarchive, :edit]
  # GET /patients
  # GET /patients.xml
  def index
    respond_to do |format|
      format.html {}
      format.json {
        @patients = Patient.where(:archive => false).jtable_basic_query(params[:jTableQuery])
        render :json => jtable_for_json(:basic, @patients, params[:jTableQuery])
      }
      format.xml  { render :xml => @icd_codes }
      format.xls  {@patients = Patient.all}
    end
  end
  
  def archived
    respond_to do |format|
      format.html {}
      format.json {
        @patients = Patient.where(:archive => true).jtable_basic_query(params[:jTableQuery])
        render :json => jtable_for_json(:basic, @patients, params[:jTableQuery])
      }
      format.xml  { render :xml => @icd_codes }
    end
  end

  # GET /patients/1
  # GET /patients/1.xml
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html { render :layout => false }
      format.xml  { render :xml => @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.xml
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.xml
  def create
    if params[:patient][:upload]
      file = params[:patient][:upload].read
      file.each_line do |patient|
        name, age, sex, treatment, address, source = patient.chomp.split(",")
        Patient.create!(:name => name, :age => age, :sex => sex, :treatment => treatment, :address => address, :source => source)
      end
      redirect_to(patients_url)
    else
      @patient = Patient.new(params[:patient])
      respond_to do |format|
        if @patient.save
          format.html { redirect_to(@patient, :notice => 'Patient was successfully created.') }
          format.xml  { render :xml => @patient, :status => :created, :location => @patient }
        else
          format.html { render :action => "new" }
          format.xml  { render :xml => @patient.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.xml
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to(@patient, :notice => 'Patient was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @patient.errors, :status => :unprocessable_entity }
      end
    end
  end

  def upload
    @patient = Patient.new
  end
  
  def archive
    @patient = Patient.find(params[:id])
    @patient.archive = true
    @patient.save
    
    respond_to do |format|
      format.html {redirect_to(patients_url) }
    end
  end
  
  def unarchive
    @patient = Patient.find(params[:id])
    @patient.archive = false
    @patient.save
    
    respond_to do |format|
      format.html {redirect_to(archived_patients_path) }
    end
  end
  
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient, :html => {:multipart => true}) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :sex %><br />
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :treatment %><br />
    <%= f.text_field :treatment %>
  </div>
  <div class="field">
    <%= f.label :source %><br />
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :plhiv_code %><br />
    <%= f.text_field :plhiv_code %>
  </div>
  <div class="field">
    <%= f.label :plhiv_name %><br />
    <%= f.text_field :plhiv_name %>
  </div>
  <div class="field">
    <%= f.label :support_group %><br />
    <%= f.text_field :support_group %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :treatment_code %><br />
    <%= f.text_field :treatment_code %>
  </div>
  <div class="field">
    <%= f.label :occupation %><br />
    <%= f.text_field :occupation %>
  </div>
  <div class="field">
    <%= f.label :marital_status %><br />
    <%= f.text_field :marital_status %>
  </div>
  <div class="field">
    <%= f.label :children %><br />
    <%= f.text_field :children%>
  </div>
  <div class="field">
    <%= f.label :line_of_treatment %><br />
    <%= f.text_field :line_of_treatment %>
  </div>
  <div class="field">
    <%= f.label :next_of_kin_contact %><br />
    <%= f.text_field :next_of_kin_contact %>
  </div>
  <div class="field">
    <%= f.label :disclosed_status %><br />
    <%= f.text_field :disclosed_status %>
  </div>
  <div class="field">
    <%= f.label :transfer_in %><br />
    <%= f.text_field :transfer_in %>
  </div>
  <div class="field">
    <%= f.label :transfer_out %><br />
    <%= f.text_field :transfer_out %>
  </div>
  <div class="field">
    <%= f.label :co_infected %><br />
    <%= f.text_field :co_infected %>
  </div>
  <div class="field">
    <%= f.label :treatment_default %><br />
    <%= f.text_field :treatment_default %>
  </div>
  <div class="field">
    <%= f.label :type_of_service_received %><br />
    <%= f.text_field :type_of_service_received %>
  </div> 
  <div class="field">
    <%= f.label :deceased %>
    <%= f.check_box :deceased %>
  </div> 
  <div class="field">
    <%= f.label "Upload Picture" %><br />
    <%= f.file_field :picture %>
  </div> 

  <%= image_tag @patient.picture.url unless @patient.picture.url.blank? %>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/patients/archived.html.erb
<h1>Listing archived adult patients</h1>

<div id="patients"></div>
<script type="text/javascript" charset="utf-8">
  $('#patients').jTable({
    width: '100%',
    indexUrl: '/patients/archived.json',
    viewUrl: '/patients/:id:',
    editUrl: '/patients/:id:/edit',
    destroyLink: false,
    singleColumnSearch: true,
    columns: [
      {heading: 'Name', attribute: 'name'},
      {heading: 'Address', attribute: 'address'},
      {heading: 'Age', attribute: 'age'},
      {heading: 'Sex', attribute: 'sex'},
      {heading: 'Treatment', attribute: 'treatment'},
      {heading: 'Source', attribute: 'source'},
      {heading: 'Has Picture', attribute: 'picture', dataType: 'boolean', trueValue: 'Yes', falseValue: 'No'}
    ],
    otherActions: [
      {title: 'Restore', href: '/patients/:id:/unarchive'}
    ]
  })
</script>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<div id="patients"></div>
<script type="text/javascript" charset="utf-8">
  $('#patients').jTable({
    width: '100%',
    indexUrl: '/patients.json',
    viewUrl: '/patients/:id:',
    editUrl: '/patients/:id:/edit',
    destroyLink: false,
    singleColumnSearch: true,
    columns: [
      {heading: 'Name', attribute: 'name'},
      {heading: 'Address', attribute: 'address'},
      {heading: 'Age', attribute: 'age'},
      {heading: 'Sex', attribute: 'sex'},
      {heading: 'Treatment', attribute: 'treatment'},
      {heading: 'Source', attribute: 'source'},
      {heading: 'Has Picture', attribute: 'picture', dataType: 'boolean', trueValue: 'Yes', falseValue: 'No'}
    ],
    otherActions: [
      {title: 'Archive', href: '/patients/:id:/archive'}
    ]
  })
</script>

<br />
<%= link_to "Archived Patients", archived_patients_path %><br />
<%= link_to 'New Patient', new_patient_path %><br />
<%= link_to "Upload Patients File", upload_patients_path %><br />
<%= link_to "Download Adults as Excel", patients_path(:format => :xls) %> 

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @patient.name %>
</p>

<p>
  <b>Address:</b>
  <%= @patient.address %>
</p>

<p>
  <b>Telephone  Number:</b>
  <%= @patient.telephone %>
</p>

<p>
  <b>Age:</b>
  <%= @patient.age %>
</p>

<p>
  <b>Sex:</b>
  <%= @patient.sex %>
</p>

<p>
  <b>Treatment:</b>
  <%= @patient.treatment %>
</p>

<p>
  <b>Source:</b>
  <%= @patient.source %>
</p>

<p>
  <b>PLHIV Code:</b>
  <%= @patient.plhiv_code %>
</p>

<p>
  <b>PLHIV Name:</b>
  <%= @patient.plhiv_name %>
</p>

<p>
  <b>Support Group:</b>
  <%= @patient.support_group %>
</p>

<p>
  <b>Weight:</b>
  <%= @patient.weight %>
</p>

<p>
  <b>Treatment Code:</b>
  <%= @patient.treatment_code %>
</p>

<p>
  <b>Occupation:</b>
  <%= @patient.occupation %>
</p>

<p>
  <b>Marital Status:</b>
  <%= @patient.marital_status %>
</p>

<p>
  <b>Children:</b>
  <%= @patient.children %>
</p>

<p>
  <b>Line of Treatment:</b>
  <%= @patient.line_of_treatment %>
</p>

<p>
  <b>Next of Kin/Contact:</b>
  <%= @patient.next_of_kin_contact %>
</p>

<p>
  <b>Disclosed Status:</b>
  <%= @patient.disclosed_status %>
</p>

<p>
  <b>Transfer In:</b>
  <%= @patient.transfer_in %>
</p>

<p>
  <b>Transfer Out:</b>
  <%= @patient.transfer_out %>
</p>

<p>
  <b>Co Infected:</b>
  <%= @patient.co_infected %>
</p>

<p>
  <b>Treatment Default:</b>
  <%= @patient.treatment_default %>
</p>

<p>
  <b>Type of Service Received:</b>
  <%= @patient.type_of_service_received %>
</p>

<p>
  <b>Deceased:</b>
  <% if @patient.deceased.blank? || @patient.deceased == "0"%> 
      <%= 'N' %>
    <% else %>
      <%= 'Y' %>
  <% end %>
</p>

<%= image_tag @patient.picture.url unless @patient.picture.url.blank? %><br />
<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patient_path %>

app/views/patients/upload.html.erb
<%= form_for(@patient, :html => {:multipart => true}) do |f| %>
  <div class="field">
    <%= f.label :upload, "Upload csv file in the format of 'name, address, telephone number, age, sex, treatment, source, plhiv code, plhiv name, support group, weight, treatment code, date_registered, occupation, marital status, children, line of treatment, next of kin, disclosed status, transfer in, transfer out, co infected, treatment default, type of service received, deceased' to add to the patient database"%><br /><br /><br />
    
    <%= f.file_field :upload %>
  </div>
  <div class="actions">
    <%= f.submit("Upload") %>
  </div>
<% end %>